# Generated by Django 2.2.5 on 2022-03-03 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220303_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Address',
            new_name='address',
        ),
    ]
